# Generated by Django 4.2.24 on 2025-09-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('game_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FIB', 'Fill in the Blanks'), ('SEQ', 'Sequencing'), ('DND', 'Drag and Drop')], max_length=5)),
                ('config', models.JSONField(default=dict, help_text='Game-specific settings like time limit, scoring rules')),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('options', models.JSONField(help_text='List of choices for MCQ, or parts for sequencing')),
                ('answer', models.JSONField(help_text='Correct answer(s)')),
                ('hint', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.PositiveSmallIntegerField(default=1, help_text='1-5 scale')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.game')),
            ],
        ),
    ]
