# Generated by Django 4.2.24 on 2025-09-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 6, 7, 12', max_length=20, unique=True)),
                ('display_name', models.CharField(help_text='e.g., Grade 6, Senior Year', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order for display')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
